name: Build Dev & Deploy Pages

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  release:
    name: Build Website & Deploy
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.2.3
        with:
          fetch-depth: 0
          persist-credentials: false # 关闭默认凭证，改用配置token

      - name: Install Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "22.x"

      - name: Copy .env.example
        run: |
          if (-not (Test-Path .env)) {
            Copy-Item .env.example .env
          } else {
            Write-Host ".env file already exists. Skipping the copy step."
          }

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Home-Dist
          path: ./dist

      # 关键：配置git用户名邮箱 + 传入token授权，解决git 128
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
